export const SET_INFORMATION_ADMIN = "SET_INFORMATION_ADMIN";
export const GET_PROFILE_ADMIN = "GET_PROFILE_ADMIN";
export const GET_PROFILE_ADMIN_FAIL = "GET_PROFILE_ADMIN_FAIL";
export const GET_PROFILE_ADMIN_SUCCEED = "GET_PROFILE_ADMIN_SUCCEED";
