export const SET_INFORMATION_ADMIN = "SET_INFORMATION_ADMIN";
export const GET_INFORMATION_ADMIN = "GET_INFORMATION_ADMIN";
export const GET_INFORMATION_ADMIN_FAIL = "GET_INFORMATION_ADMIN_FAIL";
export const GET_INFORMATION_ADMIN_SUCCEED = "GET_INFORMATION_ADMIN_SUCCEED";
