export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCEED = "FORGOT_PASSWORD_SUCCEED";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCEED = "RESET_PASSWORD_SUCCEED";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCEED = "REGISTER_SUCCEED";
export const REGISTER_FAIL = "REGISTER_FAIL";

// auth done
export const GET_AUTH_USER = "GET_AUTH_USER";
export const GET_AUTH_USER_SUCCESS = "GET_AUTH_USER_SUCCESS";
export const GET_AUTH_USER_FAIL = "GET_AUTH_USER_FAIL";

// admin
export const ADMIN_LOGIN_API = "ADMIN_LOGIN_API";
export const ADMIN_LOGIN_API_SUCCEED = "ADMIN_LOGIN_API_SUCCEED";
export const ADMIN_LOGIN_API_FAIL = "ADMIN_LOGIN_API_FAIL";

export const CREATE_NEW_ADMIN_ACCOUNT = "CREATE_NEW_ADMIN_ACCOUNT";
export const CREATE_NEW_ADMIN_ACCOUNT_SUCCEED =
  "CREATE_NEW_ADMIN_ACCOUNT_SUCCEED";
export const CREATE_NEW_ADMIN_ACCOUNT_FAIL = "CREATE_NEW_ADMIN_ACCOUNT_FAIL";

export const ADMIN_FORGOT_PASSWORD = "ADMIN_FORGOT_PASSWORD";
export const ADMIN_FORGOT_PASSWORD_SUCCEED = "ADMIN_FORGOT_PASSWORD_SUCCEED";
export const ADMIN_FORGOT_PASSWORD_FAIL = "ADMIN_FORGOT_PASSWORD_FAIL";

export const ADMIN_RESET_PASSWORD = "ADMIN_RESET_PASSWORD";
export const ADMIN_RESET_PASSWORD_SUCCEED = "ADMIN_RESET_PASSWORD_SUCCEED";
export const ADMIN_RESET_PASSWORD_FAIL = "ADMIN_RESET_PASSWORD_FAIL";
