export const CREATE_CART = "CREATE_CART";
export const CREATE_CART_FAIL = "CREATE_CART_FAIL";
export const CREATE_CART_SUCCEED = "CREATE_CART_SUCCEED";
//
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";
export const UPDATE_CART_SUCCEED = "UPDATE_CART_SUCCEED";
//
export const GET_LIST_CART = "GET_LIST_CART";
export const GET_LIST_CART_FAIL = "GET_LIST_CART_FAIL";
export const GET_LIST_CART_SUCCEED = "GET_LIST_CART_SUCCEED";
//
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";
export const DELETE_CART_SUCCEED = "DELETE_CART_SUCCEED";
//
export const DELETE_ALL_CART = "DELETE_ALL_CART";
export const DELETE_ALL_CART_FAIL = "DELETE_ALL_CART_FAIL";
export const DELETE_ALL_CART_SUCCEED = "DELETE_ALL_CART_SUCCEED";
