export const CREATE_CERTIFICATION = "CREATE_CERTIFICATION";
export const CREATE_CERTIFICATION_FAIL = "CREATE_CERTIFICATION_FAIL";
export const CREATE_CERTIFICATION_SUCCEED = "CREATE_CERTIFICATION_SUCCEED";

export const UPDATE_CERTIFICATION_BY_ID = "UPDATE_CERTIFICATION_BY_ID";
export const UPDATE_CERTIFICATION_BY_ID_FAIL =
  "UPDATE_CERTIFICATION_BY_ID_FAIL";
export const UPDATE_CERTIFICATION_BY_ID_SUCCEED =
  "UPDATE_CERTIFICATION_BY_ID_SUCCEED";

export const REMOVE_CERTIFICATION_BY_ID = "REMOVE_CERTIFICATION_BY_ID";
export const REMOVE_CERTIFICATION_BY_ID_FAIL =
  "REMOVE_CERTIFICATION_BY_ID_FAIL";
export const REMOVE_CERTIFICATION_BY_ID_SUCCEED =
  "REMOVE_CERTIFICATION_BY_ID_SUCCEED";

export const GET_LIST_CERTIFICATION_PER_PAGE =
  "GET_LIST_CERTIFICATION_PER_PAGE";
export const GET_LIST_CERTIFICATION_PER_PAGE_FAIL =
  "GET_LIST_CERTIFICATION_PER_PAGE_FAIL";
export const GET_LIST_CERTIFICATION_PER_PAGE_SUCCEED =
  "GET_LIST_CERTIFICATION_PER_PAGE_SUCCEED";

export const GET_CERTIFICATION_BY_ID = "GET_CERTIFICATION_BY_ID";
export const GET_CERTIFICATION_BY_ID_FAIL = "GET_CERTIFICATION_BY_ID_FAIL";
export const GET_CERTIFICATION_BY_ID_SUCCEED =
  "GET_CERTIFICATION_BY_ID_SUCCEED";
