export const SET_TOKEN = "SET_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_IMAGE_USER = "SET_IMAGE_USER";

export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCEED = "GET_TOKEN_SUCCEED";
export const GET_TOKEN_FAIL = "GET_TOKEN_FAIL";
// profile
export const SET_INFORMATION_USER = "SET_INFORMATION_USER";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PROFILE_SUCCEED = "GET_PROFILE_SUCCEED";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_SUCCEED = "UPDATE_PROFILE_SUCCEED";

export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const UPDATE_AVATAR_FAIL = "UPDATE_AVATAR_FAIL";
export const UPDATE_AVATAR_SUCCEED = "UPDATE_AVATAR_SUCCEED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_SUCCEED = "CHANGE_PASSWORD_SUCCEED";
