export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_SUCCEED = "CREATE_COURSE_SUCCEED";

export const UPDATE_COURSE_BY_ID = "UPDATE_COURSE_BY_ID";
export const UPDATE_COURSE_BY_ID_FAIL = "UPDATE_COURSE_BY_ID_FAIL";
export const UPDATE_COURSE_BY_ID_SUCCEED = "UPDATE_COURSE_BY_ID_SUCCEED";

export const REMOVE_COURSE_BY_ID = "REMOVE_COURSE_BY_ID";
export const REMOVE_COURSE_BY_ID_FAIL = "REMOVE_COURSE_BY_ID_FAIL";
export const REMOVE_COURSE_BY_ID_SUCCEED = "REMOVE_COURSE_BY_ID_SUCCEED";

export const GET_LIST_COURSE_PER_PAGE = "GET_LIST_COURSE_PER_PAGE";
export const GET_LIST_COURSE_PER_PAGE_FAIL = "GET_LIST_COURSE_PER_PAGE_FAIL";
export const GET_LIST_COURSE_PER_PAGE_SUCCEED =
  "GET_LIST_COURSE_PER_PAGE_SUCCEED";

export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const GET_COURSE_BY_ID_FAIL = "GET_COURSE_BY_ID_FAIL";
export const GET_COURSE_BY_ID_SUCCEED = "GET_COURSE_BY_ID_SUCCEED";

export const GET_EXAMINATION_BY_COURSE_ID = "GET_EXAMINATION_BY_COURSE_ID";
export const GET_EXAMINATION_BY_COURSE_ID_FAIL =
  "GET_EXAMINATION_BY_COURSE_ID_FAIL";
export const GET_EXAMINATION_BY_COURSE_ID_SUCCEED =
  "GET_EXAMINATION_BY_COURSE_ID_SUCCEED";
