export const GET_LIST_CUSTOMERS = "GET_LIST_CUSTOMERS";
export const GET_LIST_CUSTOMERS_FAIL = "GET_LIST_CUSTOMERS_FAIL";
export const GET_LIST_CUSTOMERS_SUCCEED = "GET_LIST_CUSTOMERS_SUCCEED";

export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID";
export const GET_CUSTOMER_BY_ID_FAIL = "GET_CUSTOMER_BY_ID_FAIL";
export const GET_CUSTOMER_BY_ID_SUCCEED = "GET_CUSTOMER_BY_ID_SUCCEED";

export const BAN_OR_UN_BAN_CUSTOMERS = "BAN_OR_UN_BAN_CUSTOMERS";
export const BAN_OR_UN_BAN_CUSTOMERS_FAIL = "BAN_OR_UN_BAN_CUSTOMERS_FAIL";
export const BAN_OR_UN_BAN_CUSTOMERS_SUCCEED =
  "BAN_OR_UN_BAN_CUSTOMERS_SUCCEED";
