export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const CREATE_EMPLOYEE_FAIL = "CREATE_EMPLOYEE_FAIL";
export const CREATE_EMPLOYEE_SUCCEED = "CREATE_EMPLOYEE_SUCCEED";

export const GET_LIST_EMPLOYEES = "GET_LIST_EMPLOYEES";
export const GET_LIST_EMPLOYEES_FAIL = "GET_LIST_EMPLOYEES_FAIL";
export const GET_LIST_EMPLOYEES_SUCCEED = "GET_LIST_EMPLOYEES_SUCCEED";

export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
export const GET_EMPLOYEE_BY_ID_FAIL = "GET_EMPLOYEE_BY_ID_FAIL";
export const GET_EMPLOYEE_BY_ID_SUCCEED = "GET_EMPLOYEE_BY_ID_SUCCEED";

export const BAN_OR_UN_BAN_EMPLOYEES = "BAN_OR_UN_BAN_EMPLOYEES";
export const BAN_OR_UN_BAN_EMPLOYEES_FAIL = "BAN_OR_UN_BAN_EMPLOYEES_FAIL";
export const BAN_OR_UN_BAN_EMPLOYEES_SUCCEED =
  "BAN_OR_UN_BAN_EMPLOYEES_SUCCEED";

export const DELETE_EMPLOYEES = "DELETE_EMPLOYEES";
export const DELETE_EMPLOYEES_FAIL = "DELETE_EMPLOYEES_FAIL";
export const DELETE_EMPLOYEES_SUCCEED = "DELETE_EMPLOYEE_BY_ID_SUCCEED";
