export const GET_ALL_FEEDBACKS_BY_ITEM_ID = "GET_ALL_FEEDBACKS_BY_ITEM_ID";
export const GET_ALL_FEEDBACKS_BY_ITEM_ID_FAIL =
  "GET_ALL_FEEDBACKS_BY_ITEM_ID_FAIL";
export const GET_ALL_FEEDBACKS_BY_ITEM_ID_SUCCEED =
  "GET_ALL_FEEDBACKS_BY_ITEM_ID_SUCCEED";

export const SYSTEM_REPLY = "SYSTEM_REPLY";
export const SYSTEM_REPLY_FAIL = "SYSTEM_REPLY_FAIL";
export const SYSTEM_REPLY_SUCCEED = "SYSTEM_REPLY_SUCCEED";

export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const ADD_FEEDBACK_FAIL = "ADD_FEEDBACK_FAIL";
export const ADD_FEEDBACK_SUCCEED = "ADD_FEEDBACK_SUCCEED";
