export const CREATE_FOOD = "CREATE_FOOD";
export const CREATE_FOOD_FAIL = "CREATE_FOOD_FAIL";
export const CREATE_FOOD_SUCCEED = "CREATE_FOOD_SUCCEED";

export const UPDATE_FOOD_BY_ID = "UPDATE_FOOD_BY_ID";
export const UPDATE_FOOD_BY_ID_FAIL = "UPDATE_FOOD_BY_ID_FAIL";
export const UPDATE_FOOD_BY_ID_SUCCEED = "UPDATE_FOOD_BY_ID_SUCCEED";

export const REMOVE_TEMP_BY_ID = "REMOVE_TEMP_BY_ID";
export const REMOVE_TEMP_BY_ID_FAIL = "REMOVE_TEMP_BY_ID_FAIL";
export const REMOVE_TEMP_BY_ID_SUCCEED = "REMOVE_TEMP_BY_ID_SUCCEED";

export const GET_LIST_FOOD_PER_PAGE = "GET_LIST_FOOD_PER_PAGE";
export const GET_LIST_FOOD_PER_PAGE_FAIL = "GET_LIST_FOOD_PER_PAGE_FAIL";
export const GET_LIST_FOOD_PER_PAGE_SUCCEED = "GET_LIST_FOOD_PER_PAGE_SUCCEED";

export const EXPORT_FOOD_LIST = "EXPORT_FOOD_LIST";
export const EXPORT_FOOD_LIST_FAIL = "EXPORT_FOOD_LIST_FAIL";
export const EXPORT_FOOD_LIST_SUCCEED = "EXPORT_FOOD_LIST_SUCCEED";

export const GET_FOOD_BY_ID = "GET_FOOD_BY_ID";
export const GET_FOOD_BY_ID_FAIL = "GET_FOOD_BY_ID_FAIL";
export const GET_FOOD_BY_ID_SUCCEED = "GET_FOOD_BY_ID_SUCCEED";

export const RESET_TO_SEARCH_FOOD = "RESET_TO_SEARCH_FOOD";
