export const PAYPAL_CREATE = "PAYPAL_CREATE";
export const PAYPAL_CREATE_FAIL = "PAYPAL_CREATE_FAIL";
export const PAYPAL_CREATE_SUCCEED = "PAYPAL_CREATE_SUCCEED";

export const PAYPAL_EXECUTE = "PAYPAL_EXECUTE";
export const PAYPAL_EXECUTE_FAIL = "PAYPAL_EXECUTE_FAIL";
export const PAYPAL_EXECUTE_SUCCEED = "PAYPAL_EXECUTE_SUCCEED";
