// FOOD
export const PAYPAL_EXECUTE = "PAYPAL_EXECUTE";
export const PAYPAL_EXECUTE_FAIL = "PAYPAL_EXECUTE_FAIL";
export const PAYPAL_EXECUTE_SUCCEED = "PAYPAL_EXECUTE_SUCCEED";
// COURSE
export const PAYPAL_EXECUTE_COURSE = "PAYPAL_EXECUTE_COURSE";
export const PAYPAL_EXECUTE_COURSE_FAIL = "PAYPAL_EXECUTE_COURSE_FAIL";
export const PAYPAL_EXECUTE_COURSE_SUCCEED = "PAYPAL_EXECUTE_COURSE_SUCCEED";
// REDIRECT MONEY
export const PAYMENT_DIRECT_MONEY = "PAYMENT_DIRECT_MONEY";
export const PAYMENT_DIRECT_MONEY_FAIL = "PAYMENT_DIRECT_MONEY_FAIL";
export const PAYMENT_DIRECT_MONEY_SUCCEED = "PAYMENT_DIRECT_MONEY_SUCCEED";
// GET ALL ORDERS ADMINISTRATOR
export const GET_ALL_ORDERS_ADMINISTRATOR = "GET_ALL_ORDERS_ADMINISTRATOR";
export const GET_ALL_ORDERS_ADMINISTRATOR_FAIL =
  "GET_ALL_ORDERS_ADMINISTRATOR_FAIL";
export const GET_ALL_ORDERS_ADMINISTRATOR_SUCCEED =
  "GET_ALL_ORDERS_ADMINISTRATOR_SUCCEED";
// GET ALL ORDERS CLIENT
export const GET_ALL_ORDERS_CLIENT = "GET_ALL_ORDERS_CLIENT";
export const GET_ALL_ORDERS_CLIENT_FAIL = "GET_ALL_ORDERS_CLIENT_FAIL";
export const GET_ALL_ORDERS_CLIENT_SUCCEED = "GET_ALL_ORDERS_CLIENT_SUCCEED";
// UPDATE STATUS
export const UPDATE_STATUS_ORDER = "UPDATE_STATUS_ORDER";
export const UPDATE_STATUS_ORDER_FAIL = "UPDATE_STATUS_ORDER_FAIL";
export const UPDATE_STATUS_ORDER_SUCCEED = "UPDATE_STATUS_ORDER_SUCCEED";

export const CHECK_EXIST_IN_MY_COURSES = "CHECK_EXIST_IN_MY_COURSES";
export const CHECK_EXIST_IN_MY_COURSES_FAIL = "CHECK_EXIST_IN_MY_COURSES_FAIL";
export const CHECK_EXIST_IN_MY_COURSES_SUCCEED =
  "CHECK_EXIST_IN_MY_COURSES_SUCCEED";
