export const CREATE_RECIPE = "CREATE_RECIPE";
export const CREATE_RECIPE_FAIL = "CREATE_RECIPE_FAIL";
export const CREATE_RECIPE_SUCCEED = "CREATE_RECIPE_SUCCEED";

export const UPDATE_RECIPE_BY_ID = "UPDATE_RECIPE_BY_ID";
export const UPDATE_RECIPE_BY_ID_FAIL = "UPDATE_RECIPE_BY_ID_FAIL";
export const UPDATE_RECIPE_BY_ID_SUCCEED = "UPDATE_RECIPE_BY_ID_SUCCEED";

export const REMOVE_RECIPE_BY_ID = "REMOVE_RECIPE_BY_ID";
export const REMOVE_RECIPE_BY_ID_FAIL = "REMOVE_RECIPE_BY_ID_FAIL";
export const REMOVE_RECIPE_BY_ID_SUCCEED = "REMOVE_RECIPE_BY_ID_SUCCEED";

export const GET_LIST_RECIPE_PER_PAGE = "GET_LIST_RECIPE_PER_PAGE";
export const GET_LIST_RECIPE_PER_PAGE_FAIL = "GET_LIST_RECIPE_PER_PAGE_FAIL";
export const GET_LIST_RECIPE_PER_PAGE_SUCCEED =
  "GET_LIST_RECIPE_PER_PAGE_SUCCEED";

export const GET_RECIPE_BY_ID = "GET_RECIPE_BY_ID";
export const GET_RECIPE_BY_ID_FAIL = "GET_RECIPE_BY_ID_FAIL";
export const GET_RECIPE_BY_ID_SUCCEED = "GET_RECIPE_BY_ID_SUCCEED";
