export const GET_REVENUES_INFO = "GET_REVENUES_INFO";
export const GET_REVENUES_INFO_FAIL = "GET_REVENUES_INFO_FAIL";
export const GET_REVENUES_INFO_SUCCEED = "GET_REVENUES_INFO_SUCCEED";

export const GET_GENERAL_INFO = "GET_GENERAL_INFO";
export const GET_GENERAL_INFO_FAIL = "GET_GENERAL_INFO_FAIL";
export const GET_GENERAL_INFO_SUCCEED = "GET_GENERAL_INFO_SUCCEED";
