export const CREATE_VOUCHER = "CREATE_VOUCHER";
export const CREATE_VOUCHER_FAIL = "CREATE_VOUCHER_FAIL";
export const CREATE_VOUCHER_SUCCEED = "CREATE_VOUCHER_SUCCEED";

export const UPDATE_VOUCHER_BY_ID = "UPDATE_VOUCHER_BY_ID";
export const UPDATE_VOUCHER_BY_ID_FAIL = "UPDATE_VOUCHER_BY_ID_FAIL";
export const UPDATE_VOUCHER_BY_ID_SUCCEED = "UPDATE_VOUCHER_BY_ID_SUCCEED";

export const REMOVE_VOUCHER_BY_ID = "REMOVE_VOUCHER_BY_ID";
export const REMOVE_VOUCHER_BY_ID_FAIL = "REMOVE_VOUCHER_BY_ID_FAIL";
export const REMOVE_VOUCHER_BY_ID_SUCCEED = "REMOVE_VOUCHER_BY_ID_SUCCEED";

export const GET_LIST_VOUCHER_PER_PAGE = "GET_LIST_VOUCHER_PER_PAGE";
export const GET_LIST_VOUCHER_PER_PAGE_FAIL = "GET_LIST_VOUCHER_PER_PAGE_FAIL";
export const GET_LIST_VOUCHER_PER_PAGE_SUCCEED =
  "GET_LIST_VOUCHER_PER_PAGE_SUCCEED";

export const GET_VOUCHER_BY_ID = "GET_VOUCHER_BY_ID";
export const GET_VOUCHER_BY_ID_FAIL = "GET_VOUCHER_BY_ID_FAIL";
export const GET_VOUCHER_BY_ID_SUCCEED = "GET_VOUCHER_BY_ID_SUCCEED";

export const GET_LIST_VOUCHERS_CLIENT = "GET_LIST_VOUCHERS_CLIENT";
export const GET_LIST_VOUCHERS_CLIENT_FAIL = "GET_LIST_VOUCHERS_CLIENT_FAIL";
export const GET_LIST_VOUCHERS_CLIENT_SUCCEED =
  "GET_LIST_VOUCHERS_CLIENT_SUCCEED";
