export const GET_LIST_WISHLIST = "GET_LIST_WISHLIST";
export const GET_LIST_WISHLIST_FAIL = "GET_LIST_WISHLIST_FAIL";
export const GET_LIST_WISHLIST_SUCCEED = "GET_LIST_WISHLIST_SUCCEED";
//
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const UPDATE_WISHLIST_FAIL = "UPDATE_WISHLIST_FAIL";
export const UPDATE_WISHLIST_SUCCEED = "UPDATE_WISHLIST_SUCCEED";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
